### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by nomandia** [spmjs/docs#14]
可能是个低级问题，但真的是很令人头疼
D:\spm\test>spm install seajs

C:\Users\PC\AppData\Roaming\npm\node_modules\spm\node_modules\co\index.js:50
return new Promise(function(resolve, reject) {
^
ReferenceError: Promise is not defined
at co (C:\Users\PC\AppData\Roaming\npm\node_modules\spm\node_modules\co\index.js:50:14)
at createPromise (C:\Users\PC\AppData\Roaming\npm\node_modules\spm\node_modules\co\index.js:30:15)
at Object. (C:\Users\PC\AppData\Roaming\npm\node_modules\spm\bin\spm-install:43:1)
at Module.compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:929:3
我在执行 spm install seajs 时一直报这个错误，不知道怎么回事。我用npm cnpm都试过重新安装 spm，但还是不成，求教@@

**Comment by soda-x** [comment]
怀疑可能是你的node版本的问题. 可以尝试使用 0.12.0的版本 试试

**Comment by ishenli** [comment]
恩，应该是你的node不支持原生Promise吧。。升级一下node应该就可以了

**Comment by nomandia** [comment]
这个后来重装了nodejs，版本是4.xx，之前的太老了。windows下及centos下都是这个问题。
